all:

gem:
	cd ../slidemovie; listfiles cli.py core.py > ~/Downloads/slidemovie-code.txt
	cd ../docs; listfiles *.md > ~/Downloads/slidemovie-docs.txt
	cd ../docs/ja; listfiles *.md > ~/Downloads/slidemovie-docs-ja.txt
